name: omniORB Formula Build

on: [push]

jobs:
  build:
    name: omniORB Formula build on macOS (x86_64)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          echo "Setting up Homebrew for Intel"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/usr/local/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/usr/local/bin/brew shellenv)"
      
      - name: Install dependencies
        run: |
          brew install openssl@3

      - name: Build project
        run: |
          ls -R
          build.sh

  build-apple-silicon:
    name: omniORB Formula build on macOS (ARM64)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          echo "Setting up Homebrew for Apple Silicon"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install dependencies
        run: |
          ls -R
          brew install openssl@3

      - name: Build project
        run: |
          build.sh
